---
title: "JSM 2019"
---

Technological advances have made many wearable devices available for use in large epidemiological cohorts, national biobanks, and clinical studies. This opens up a tremendous opportunity for clinical and public health researchers to unveil previously hidden but pivotal physiological and behavioral signatures and relate them to disability and disease. Therefore, understanding, interpretation and analysis of complex multimodal and multilevel data produced by such devices becomes crucial. The main goal of this course is to present an overview of the functional data analysis methods for modeling physical activity data, review their strengths and limitations, and demonstrate their implementation in R packages refund and mgcv. We will also examine several non-functional approaches for extracting informative and interpretable features from wearable data. We will discuss applications in epidemiological studies such as [Head Start Program](https://journals.lww.com/acsm-msse/fulltext/2016/09000/New_Insights_into_Activity_Patterns_in_Children,.11.aspx) and [National Health and Nutrition Examination Survey](https://link.springer.com/article/10.1007/s12561-018-09229-9) and a clinical study of [Congestive Heart Failure](https://www.tandfonline.com/doi/full/10.1080/01621459.2018.1482750).

This page contains materials by [Vadim Zipunnikov](http://www.biostat.jhsph.edu/~vzipunni/) and [Jeff Goldsmith](http://jeffgoldsmith.com) for the JSM 2019 continuing education course titled ["Functional Data Analysis for Wearables: Methods and Applications"](https://ww2.amstat.org/meetings/jsm/2019/onlineprogram/ActivityDetails.cfm?SessionID=218199).
