---
title: "Data and Code"
output:
  html_document: 
    code_folding: hide
    toc: true
    toc_float: true
---

Two datasets will be used in the short course. They are below with brief descriptions.

## NHANES Data

The National Health and Nutrition Examination Survey [(NHANES)](https://www.cdc.gov/nchs/nhanes/index.htm)  is a cross-sectional, nationally representative survey that assesses demographic, dietary and health-related questions and can be used to better understand differences in health and nutrition across age groups.  Survey data are made publically available by the National Center for Health Statistics (NCHS).  All individuals participating in data collection provided informed consent, and the NCHS Ethics Review Board approved all survey protocols.

The [2003-2004 and 2004-2005 survey cycles (2003-2006)](https://www.sciencedirect.com/science/article/pii/S0091743517301949?via%3Dihub) collected accelerometer data for 7 consecutive days on individuals aged 6 years and older who were ambulatory.  The Actigraph AM-7164  uni-axial accelerometer was placed on an elastic belt and participants were instructed to wear the device on the right hip at all times other than during any aquatic activity, including swimming and bathing, and at bedtime.

The paper by [Leroux et al](https://link.springer.com/article/10.1007/s12561-018-09229-9) provides a framework for processing, storing, and analyzing the NHANES accelerometry data for the 2003-2004 and 2005-2006 surveys. [rnahnesdata](https://github.com/andrew-leroux/rnhanesdata) R package provides a quick set of tools to work with the NHANES accelerometry data. This course will use NHANES 2003-2006 accelerometry data [NHANES_JSM_2019](./DataCode/NHANES_JSM_2019.RData) that contains Age, BMI, Gender (Male), and self-reported disease status for Coronary Heart Disease (CHD), Congestive Heart Failure (CHF), and Diabetes in 3398 NHANES participants of age 50 years and older.


## HeadStart Data

The data description below draws heavily from [Goldsmith et al](http://jeffgoldsmith.com/Downloads/HeadStart.pdf) (2016):

Accelerometers have become an appealing alternative to self-report techniques for studying physical activity in observational studies and clinical trials, largely because of their relative objectivity. During observation periods, the devices measure electrical signals that are a proxy for acceleration. ``Activity counts" are then devised by summarizing the voltage signals across a short period known as an epoch; one-minute epochs are common. Because accelerometers can be worn comfortably and unobtrusively, they produce around-the-clock observations of many kinds of activity.

Study participants were recruited from 50 Head Start centers in northern Manhattan, the Bronx, and Brooklyn, in neighborhoods with high rates of pediatric asthma. We used a survey instrument to collect data on the children age, race, sex, asthma symptoms and other medical conditions, birth order and family-related factors, and features of the home environment.  Field staff measured the children height, weight, and skin-fold thicknesses The staff then attached the accelerometer to the children non-dominant wrist with a hospital band. We obtain $y_i(t)$ by averaging, for each $t$ separately, across the six days of observation for each child. Additionally, we aggregate into 10 minute epochs.

For data confidentiality reasons, we will work with a simulated dataset. These data are simulated to mimic real data: they use realistic covariates, coefficients based on a fitted model, and residuals based on those in a full analysis. The activity data can be found [here](./DataCode/Activity.RDA).
